SAMPLE_SIZE = 50000
HEAD = 10
PATH = './resume_corpus'
MAX_LEN = 2000
MAX_WORDS = 5000
EMBEDDING_SIZE = 300
EPOCHS = 50
NUM_THREADS = 32
GLOVE_EMBEDDING = f"/home/nimishbajaj/resume_tagger/embedding/glove.6B.{EMBEDDING_SIZE}d.txt"
FILE_TYPE = "tf"
checkpoint_path = "./training_1/cp.ckpt"
dirpath = "./models"
BASE_FP = '{}/trainsz{}_epochs{}'.format(dirpath, SAMPLE_SIZE, EPOCHS)